backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: 'docs'
    label: 'Docs'
    folder: ''
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
