backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

local_backend: true

publish_mode: editorial_workflow

media_folder: 'docs/public/uploads'
public_folder: '/public/uploads'

collections:
  - name: 'docs'
    label: 'Docs'
    folder: 'docs'
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
